//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_image { get; set; }
        public string p_desc { get; set; }
        public Nullable<int> p_price { get; set; }
        public Nullable<int> p_fk_cat { get; set; }
        public Nullable<int> p_fk_user { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
